# InMAPData is the path to location of baseline meteorology and pollutant data.
# The path can include environment variables.
InMAPData = "${INMAP_ROOT_DIR}/cmd/inmap/testdata/testInMAPInputData.ncf"

# OutputFile is the path to the desired output shapefile location. It can
# include environment variables.
OutputFile = "${INMAP_ROOT_DIR}/cmd/inmap/testdata/output_${InMAPRunType}.shp"

[aep]
SrgSpec = "${INMAP_ROOT_DIR}/emissions/aep/testdata/srgspec_osm.json"
SrgSpecType = "OSM"
GridRef = ["${INMAP_ROOT_DIR}/emissions/aep/aeputil/testdata/gridref_osm.txt"]

[aep.InventoryConfig]
COARDSYear = 2016
InputUnits = "tons"
[aep.InventoryConfig.COARDSFiles]
	all = ["${INMAP_ROOT_DIR}/emissions/aep/testdata/emis_coards_hawaii.nc"]

[aep.SpatialConfig]
InputSR = "+proj=longlat"

# OutputVariables specifies which model variables should be included in the
# output file. Each output variable is defined by the desired name and an
# expression that can be used to calculate it
# (in the form VariableName = "Expression"). These expressions can utilize
# variables built into the model, user-defined variables, and functions.
# Available functions include:
# 'exp(x)' which applies the exponetional function e^x.
# 'log(x)' which applies the natural logarithm function log(e).
# 'log10(x)' which applies the base-10 logarithm function log10(e).
# Note: Environment variables can be used in both variable names and expressions.
[OutputVariables]
TotalPopD = "(exp(log(1.078)/10 * TotalPM25) - 1) * TotalPop * allcause / 100000"
WhitNoLatD = "(exp(log(1.078)/10 * TotalPM25) - 1) * WhiteNoLat * allcause / 100000"
BlackD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Black * allcause / 100000"
NativeD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Native * allcause / 100000"
AsianD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Asian * allcause / 100000"
LatinoD = "(exp(log(1.078)/10 * TotalPM25) - 1) * Latino * allcause / 100000"
TotalPop = "TotalPop"
TotalPM25 = "PrimaryPM25 + pNH4 + pSO4 + pNO3 + SOA"
BasePM25 = "BaselineTotalPM25"
WindSpeed = "WindSpeed"


# VarGrid provides information for specifying the variable resolution
# grid.
[VarGrid]

# VariableGridXo and VariableGridYo are the X and Y coordinates of the
# lower-left corner of the InMAP grid.
VariableGridXo= -158
VariableGridYo= 21.25

# VariableGridDx and VariableGridDy are the X and Y edge lengths of grid
# cells in the outermost nest, in meters.
VariableGridDx= 0.1
VariableGridDy= 0.1

# Xnests and Ynests specify nesting multiples in the X and Y directions.
# For instance, if Xnests and Ynests are both [100, 2, 2, 2] and
# VariableGridDy and VariableGridDx are both 40000, the outermost
# nest would have 100 grid cells in each direction with 40 km resolution,
# and there would be three levels of inner nesting, each at double the
# resolution of the previous nest, with the innermost nest having a grid
# cell length of 5 km.
Xnests= [4]
Ynests= [4]

# GridProj gives projection info for the CTM grid in Proj4 or WKT format.
GridProj= "+proj=longlat"

# CensusFile is the path to the shapefile holding population information.
CensusFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/testPopulation.shp"

# CensusPopColumns is a list of the data fields in CensusFile that should
# be included as population estimates in the model. They can be population
# of different demographics or for different population scenarios.
CensusPopColumns= ["TotalPop", "WhiteNoLat", "Black", "Native", "Asian", "Latino"]

# PopGridColumn is the name of the field in CensusFile that contains the data
# that should be compared to PopThreshold and PopDensityThreshold when determining
# if a grid cell should be split. It should typically be one of the fields
# in CensusPopColumns.
PopGridColumn= "TotalPop"

# MortalityRateFile is the path to the shapefile containing baseline
# mortality rate data.
MortalityRateFile= "${INMAP_ROOT_DIR}/cmd/inmap/testdata/testMortalityRate.shp"

# MortalityRateColumns maps the names of each input population group to the name
# of the field in MortalityRateFile that contains its respective baseline
# mortality rate, in units of deaths per year per 100,000 people. Only mortality
# rates used in output variable expressions need to be included here.
[VarGrid.MortalityRateColumns]
allcause = "TotalPop"
whnolmort = "WhiteNoLat"
blackmort = "Black"
asianmort = "Native"
nativemort = "Asian"
latinomort = "Latino"
