// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eioserve.proto

/*
Package eiopb is a generated protocol buffer package.

It is generated from these files:
	eioserve.proto

It has these top-level messages:
	Selectors
	Selection
	Point
	Rectangle
	ColorInfo
*/
package eiopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Selectors struct {
	Names  []string  `protobuf:"bytes,1,rep,name=Names" json:"Names,omitempty"`
	Values []float32 `protobuf:"fixed32,2,rep,packed,name=Values" json:"Values,omitempty"`
}

func (m *Selectors) Reset()                    { *m = Selectors{} }
func (m *Selectors) String() string            { return proto.CompactTextString(m) }
func (*Selectors) ProtoMessage()               {}
func (*Selectors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Selectors) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *Selectors) GetValues() []float32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type Selection struct {
	DemandGroup      string `protobuf:"bytes,1,opt,name=DemandGroup" json:"DemandGroup,omitempty"`
	DemandSector     string `protobuf:"bytes,2,opt,name=DemandSector" json:"DemandSector,omitempty"`
	ProductionGroup  string `protobuf:"bytes,3,opt,name=ProductionGroup" json:"ProductionGroup,omitempty"`
	ProductionSector string `protobuf:"bytes,4,opt,name=ProductionSector" json:"ProductionSector,omitempty"`
	ImpactType       string `protobuf:"bytes,5,opt,name=ImpactType" json:"ImpactType,omitempty"`
	DemandType       string `protobuf:"bytes,6,opt,name=DemandType" json:"DemandType,omitempty"`
}

func (m *Selection) Reset()                    { *m = Selection{} }
func (m *Selection) String() string            { return proto.CompactTextString(m) }
func (*Selection) ProtoMessage()               {}
func (*Selection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Selection) GetDemandGroup() string {
	if m != nil {
		return m.DemandGroup
	}
	return ""
}

func (m *Selection) GetDemandSector() string {
	if m != nil {
		return m.DemandSector
	}
	return ""
}

func (m *Selection) GetProductionGroup() string {
	if m != nil {
		return m.ProductionGroup
	}
	return ""
}

func (m *Selection) GetProductionSector() string {
	if m != nil {
		return m.ProductionSector
	}
	return ""
}

func (m *Selection) GetImpactType() string {
	if m != nil {
		return m.ImpactType
	}
	return ""
}

func (m *Selection) GetDemandType() string {
	if m != nil {
		return m.DemandType
	}
	return ""
}

type Point struct {
	X float32 `protobuf:"fixed32,1,opt,name=X" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y" json:"Y,omitempty"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Point) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Rectangle struct {
	LL *Point `protobuf:"bytes,1,opt,name=LL" json:"LL,omitempty"`
	LR *Point `protobuf:"bytes,2,opt,name=LR" json:"LR,omitempty"`
	UR *Point `protobuf:"bytes,3,opt,name=UR" json:"UR,omitempty"`
	UL *Point `protobuf:"bytes,4,opt,name=UL" json:"UL,omitempty"`
}

func (m *Rectangle) Reset()                    { *m = Rectangle{} }
func (m *Rectangle) String() string            { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()               {}
func (*Rectangle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Rectangle) GetLL() *Point {
	if m != nil {
		return m.LL
	}
	return nil
}

func (m *Rectangle) GetLR() *Point {
	if m != nil {
		return m.LR
	}
	return nil
}

func (m *Rectangle) GetUR() *Point {
	if m != nil {
		return m.UR
	}
	return nil
}

func (m *Rectangle) GetUL() *Point {
	if m != nil {
		return m.UL
	}
	return nil
}

type ColorInfo struct {
	RGB    [][]byte `protobuf:"bytes,1,rep,name=RGB,proto3" json:"RGB,omitempty"`
	Legend string   `protobuf:"bytes,2,opt,name=Legend" json:"Legend,omitempty"`
}

func (m *ColorInfo) Reset()                    { *m = ColorInfo{} }
func (m *ColorInfo) String() string            { return proto.CompactTextString(m) }
func (*ColorInfo) ProtoMessage()               {}
func (*ColorInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ColorInfo) GetRGB() [][]byte {
	if m != nil {
		return m.RGB
	}
	return nil
}

func (m *ColorInfo) GetLegend() string {
	if m != nil {
		return m.Legend
	}
	return ""
}

func init() {
	proto.RegisterType((*Selectors)(nil), "eiopb.Selectors")
	proto.RegisterType((*Selection)(nil), "eiopb.Selection")
	proto.RegisterType((*Point)(nil), "eiopb.Point")
	proto.RegisterType((*Rectangle)(nil), "eiopb.Rectangle")
	proto.RegisterType((*ColorInfo)(nil), "eiopb.ColorInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EIOServe service

type EIOServeClient interface {
	DemandGroups(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error)
	DemandSectors(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error)
	ProdGroups(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error)
	ProdSectors(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error)
	MapInfo(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*ColorInfo, error)
	Geometry(ctx context.Context, in *Selection, opts ...grpc.CallOption) (EIOServe_GeometryClient, error)
}

type eIOServeClient struct {
	cc *grpc.ClientConn
}

func NewEIOServeClient(cc *grpc.ClientConn) EIOServeClient {
	return &eIOServeClient{cc}
}

func (c *eIOServeClient) DemandGroups(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error) {
	out := new(Selectors)
	err := grpc.Invoke(ctx, "/eiopb.EIOServe/DemandGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eIOServeClient) DemandSectors(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error) {
	out := new(Selectors)
	err := grpc.Invoke(ctx, "/eiopb.EIOServe/DemandSectors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eIOServeClient) ProdGroups(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error) {
	out := new(Selectors)
	err := grpc.Invoke(ctx, "/eiopb.EIOServe/ProdGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eIOServeClient) ProdSectors(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*Selectors, error) {
	out := new(Selectors)
	err := grpc.Invoke(ctx, "/eiopb.EIOServe/ProdSectors", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eIOServeClient) MapInfo(ctx context.Context, in *Selection, opts ...grpc.CallOption) (*ColorInfo, error) {
	out := new(ColorInfo)
	err := grpc.Invoke(ctx, "/eiopb.EIOServe/MapInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eIOServeClient) Geometry(ctx context.Context, in *Selection, opts ...grpc.CallOption) (EIOServe_GeometryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EIOServe_serviceDesc.Streams[0], c.cc, "/eiopb.EIOServe/Geometry", opts...)
	if err != nil {
		return nil, err
	}
	x := &eIOServeGeometryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EIOServe_GeometryClient interface {
	Recv() (*Rectangle, error)
	grpc.ClientStream
}

type eIOServeGeometryClient struct {
	grpc.ClientStream
}

func (x *eIOServeGeometryClient) Recv() (*Rectangle, error) {
	m := new(Rectangle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for EIOServe service

type EIOServeServer interface {
	DemandGroups(context.Context, *Selection) (*Selectors, error)
	DemandSectors(context.Context, *Selection) (*Selectors, error)
	ProdGroups(context.Context, *Selection) (*Selectors, error)
	ProdSectors(context.Context, *Selection) (*Selectors, error)
	MapInfo(context.Context, *Selection) (*ColorInfo, error)
	Geometry(*Selection, EIOServe_GeometryServer) error
}

func RegisterEIOServeServer(s *grpc.Server, srv EIOServeServer) {
	s.RegisterService(&_EIOServe_serviceDesc, srv)
}

func _EIOServe_DemandGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EIOServeServer).DemandGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eiopb.EIOServe/DemandGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EIOServeServer).DemandGroups(ctx, req.(*Selection))
	}
	return interceptor(ctx, in, info, handler)
}

func _EIOServe_DemandSectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EIOServeServer).DemandSectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eiopb.EIOServe/DemandSectors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EIOServeServer).DemandSectors(ctx, req.(*Selection))
	}
	return interceptor(ctx, in, info, handler)
}

func _EIOServe_ProdGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EIOServeServer).ProdGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eiopb.EIOServe/ProdGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EIOServeServer).ProdGroups(ctx, req.(*Selection))
	}
	return interceptor(ctx, in, info, handler)
}

func _EIOServe_ProdSectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EIOServeServer).ProdSectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eiopb.EIOServe/ProdSectors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EIOServeServer).ProdSectors(ctx, req.(*Selection))
	}
	return interceptor(ctx, in, info, handler)
}

func _EIOServe_MapInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Selection)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EIOServeServer).MapInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eiopb.EIOServe/MapInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EIOServeServer).MapInfo(ctx, req.(*Selection))
	}
	return interceptor(ctx, in, info, handler)
}

func _EIOServe_Geometry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Selection)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EIOServeServer).Geometry(m, &eIOServeGeometryServer{stream})
}

type EIOServe_GeometryServer interface {
	Send(*Rectangle) error
	grpc.ServerStream
}

type eIOServeGeometryServer struct {
	grpc.ServerStream
}

func (x *eIOServeGeometryServer) Send(m *Rectangle) error {
	return x.ServerStream.SendMsg(m)
}

var _EIOServe_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eiopb.EIOServe",
	HandlerType: (*EIOServeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DemandGroups",
			Handler:    _EIOServe_DemandGroups_Handler,
		},
		{
			MethodName: "DemandSectors",
			Handler:    _EIOServe_DemandSectors_Handler,
		},
		{
			MethodName: "ProdGroups",
			Handler:    _EIOServe_ProdGroups_Handler,
		},
		{
			MethodName: "ProdSectors",
			Handler:    _EIOServe_ProdSectors_Handler,
		},
		{
			MethodName: "MapInfo",
			Handler:    _EIOServe_MapInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Geometry",
			Handler:       _EIOServe_Geometry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "eioserve.proto",
}

func init() { proto.RegisterFile("eioserve.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x5d, 0xab, 0xd3, 0x40,
	0x10, 0xbd, 0xbb, 0x31, 0xf5, 0x66, 0x1a, 0xb5, 0x2c, 0x22, 0x41, 0x44, 0xc2, 0xfa, 0x12, 0x7c,
	0xa8, 0xd2, 0xeb, 0x7d, 0xf0, 0xd5, 0x0f, 0x4a, 0x21, 0xea, 0x65, 0xeb, 0x95, 0xf6, 0x31, 0x6d,
	0xc7, 0x12, 0x48, 0xb2, 0x61, 0x93, 0x0a, 0x7d, 0xf6, 0xb7, 0xf9, 0x5b, 0xfc, 0x1b, 0xb2, 0x93,
	0xf4, 0xcb, 0xa0, 0xdc, 0xbe, 0x75, 0xce, 0x99, 0x33, 0xb3, 0x73, 0x4e, 0x03, 0x0f, 0x31, 0xd5,
	0x15, 0x9a, 0x1f, 0x38, 0x2c, 0x8d, 0xae, 0xb5, 0x70, 0x31, 0xd5, 0xe5, 0x42, 0xbe, 0x05, 0x6f,
	0x8a, 0x19, 0x2e, 0x6b, 0x6d, 0x2a, 0xf1, 0x18, 0xdc, 0xcf, 0x49, 0x8e, 0x55, 0xc0, 0x42, 0x27,
	0xf2, 0x54, 0x53, 0x88, 0x27, 0xd0, 0xfb, 0x96, 0x64, 0x1b, 0xac, 0x02, 0x1e, 0x3a, 0x11, 0x57,
	0x6d, 0x25, 0x7f, 0xb3, 0x9d, 0x36, 0xd5, 0x85, 0x08, 0xa1, 0xff, 0x01, 0xf3, 0xa4, 0x58, 0x8d,
	0x8d, 0xde, 0x94, 0x01, 0x0b, 0x59, 0xe4, 0xa9, 0x63, 0x48, 0x48, 0xf0, 0x9b, 0x72, 0x4a, 0xeb,
	0x02, 0x4e, 0x2d, 0x27, 0x98, 0x88, 0xe0, 0xd1, 0x8d, 0xd1, 0xab, 0x0d, 0xcd, 0x6c, 0x26, 0x39,
	0xd4, 0xf6, 0x37, 0x2c, 0x5e, 0xc2, 0xe0, 0x00, 0xb5, 0x13, 0xef, 0x51, 0x6b, 0x07, 0x17, 0xcf,
	0x01, 0x26, 0x79, 0x99, 0x2c, 0xeb, 0xaf, 0xdb, 0x12, 0x03, 0x97, 0xba, 0x8e, 0x10, 0xcb, 0x37,
	0xaf, 0x20, 0xbe, 0xd7, 0xf0, 0x07, 0x44, 0xbe, 0x00, 0xf7, 0x46, 0xa7, 0x45, 0x2d, 0x7c, 0x60,
	0x33, 0x3a, 0x8d, 0x2b, 0x36, 0xb3, 0xd5, 0x9c, 0xae, 0xe0, 0x8a, 0xcd, 0xe5, 0x4f, 0x06, 0x9e,
	0xc2, 0x65, 0x9d, 0x14, 0xeb, 0x0c, 0xc5, 0x33, 0xe0, 0x71, 0x4c, 0xad, 0xfd, 0x91, 0x3f, 0x24,
	0xaf, 0x87, 0x34, 0x43, 0xf1, 0x38, 0x26, 0x56, 0x91, 0xb4, 0xcb, 0x2a, 0xcb, 0xde, 0x2a, 0xba,
	0xbb, 0xc3, 0xde, 0x36, 0x6c, 0x4c, 0xa7, 0x76, 0xd9, 0x58, 0x5e, 0x83, 0xf7, 0x5e, 0x67, 0xda,
	0x4c, 0x8a, 0xef, 0x5a, 0x0c, 0xc0, 0x51, 0xe3, 0x77, 0x94, 0xa6, 0xaf, 0xec, 0x4f, 0x9b, 0x65,
	0x8c, 0x6b, 0x2c, 0x56, 0xad, 0xfb, 0x6d, 0x35, 0xfa, 0xc5, 0xe1, 0xf2, 0xe3, 0xe4, 0xcb, 0xd4,
	0xfe, 0x41, 0xc4, 0x9b, 0x5d, 0x50, 0xe4, 0x74, 0x25, 0x06, 0xed, 0x96, 0x7d, 0xd8, 0x4f, 0x4f,
	0x11, 0x6d, 0x2a, 0x79, 0x21, 0xae, 0xe1, 0xc1, 0x71, 0x94, 0x77, 0x95, 0x8d, 0x00, 0x6c, 0x5e,
	0x67, 0xad, 0xba, 0x82, 0xbe, 0xd5, 0x9c, 0xb7, 0xe8, 0x15, 0xdc, 0xff, 0x94, 0x94, 0x8d, 0x2f,
	0xff, 0x14, 0xec, 0xbd, 0xa3, 0x97, 0x5d, 0x8e, 0x51, 0xe7, 0x58, 0x9b, 0xed, 0x7f, 0x14, 0xfb,
	0xc8, 0xe5, 0xc5, 0x6b, 0xb6, 0xe8, 0xd1, 0xc7, 0x75, 0xf5, 0x27, 0x00, 0x00, 0xff, 0xff, 0x82,
	0x59, 0xc8, 0xdc, 0x6e, 0x03, 0x00, 0x00,
}
