// Code generated by "stringer -type=Pollutant"; DO NOT EDIT

package slca

import "fmt"

const _Pollutant_name = "PM25NH3NOxSOxVOC"

var _Pollutant_index = [...]uint8{0, 4, 7, 10, 13, 16}

func (i Pollutant) String() string {
	if i < 0 || i >= Pollutant(len(_Pollutant_index)-1) {
		return fmt.Sprintf("Pollutant(%d)", i)
	}
	return _Pollutant_name[_Pollutant_index[i]:_Pollutant_index[i+1]]
}
